### ISSUE TITLE
 always send 'Accept: */*' HTTP header to webmention endpoints 

### ISSUE THREAD

**Issue by Ryuno-Ki** [Ryuno-Ki/webmention-tools#31]
I'm not happy with the approach in https://github.com/snarfed/webmention-tools/commit/a67be86024868a6e99f51be568f78505a79a1e2f
Feels fishy. I'd rather extend the Accept header to something more concrete.

@snarfed Do you happen to have more experience here by now?

**Comment by Ryuno-Ki** [comment]
See also https://github.com/snarfed/bridgy/commit/3f7d258e5313b53b074979d357c4ee61208b153b

**Comment by snarfed** [comment]
hi! hmm. not a lot more experience, no. but [webmention responses don't have to be any specific content type](https://webmention.net/draft/#receiving-webmentions) - they're actually often empty - so i wouldn't recommend that we tighten this to any concrete types. if anything, we should probably just drop `Accept: */*` altogether, since i only added it to work around my own code in Bridgy.

**Comment by Ryuno-Ki** [comment]
Hi @snarfed,

hm, I thought about it (while reading the W3C standard to ensure compliance).
I'm not feeling comfortable with allowing everything (even blobs).

What about restricting it to `text/*`?
Maybe with `application/json` in addition?
I'd then just wait for issues to be filled.

**Comment by snarfed** [comment]
hmm! for fetching source URLs, and maybe even `GET`s to webmention endpoints, i might agree. for webmention `POST`s though, again, the most common response is empty, often without `Content-Type` at all, and the spec doesn't say they have to be any specific type, as mentioned above. so i'd worry about sending any specific `Accept` value, since it might make a server think it can't satisfy the requested type(s).

(at a higher level, content negotiation (`Accept` header etc) makes me sad in general. nice idea in theory, but i suspect it's turned out to be a net negative for web development at large. much more painful and error prone than useful in practice. [more recent indieweb discussion here.](https://chat.indieweb.org/dev/2019-05-10#t1557511354346100) doesn't really matter for this question specifically though!)

**Comment by Ryuno-Ki** [comment]
Okay, have just implemented endpoint discovery. Will check the behaviour of POSTs next. Thanks for the link!

**Comment by Ryuno-Ki** [comment]
Fixed by #51
